// SPDX-FileCopyrightText: 2026 Sean Consulting OÜ
// SPDX-License-Identifier: Apache-2.0

import { AMZ_CONTENT_SHA256_HEADER, CONTENT_TYPE_HEADER, UNSIGNED_PAYLOAD, textEncoder } from "./constants.js";
import { sha256Hex } from "./crypto.js";

const typedArrayPrototype = Object.getPrototypeOf(Uint8Array.prototype) as object;

export interface PreparedBody {
  body: BodyInit | null | undefined;
  payloadHash: string;
}

interface MaterializedBody {
  body: BodyInit | null | undefined;
  bytes?: Uint8Array | undefined;
}

export interface PrepareBodyOptions {
  service: string;
  unsignedPayload: boolean;
  replay: boolean;
  signal?: AbortSignal | undefined;
}

export async function prepareSigningBody(
  body: BodyInit | null | undefined,
  headers: Headers,
  options: PrepareBodyOptions
): Promise<PreparedBody> {
  if (options.unsignedPayload && !headers.has(AMZ_CONTENT_SHA256_HEADER)) {
    headers.set(AMZ_CONTENT_SHA256_HEADER, UNSIGNED_PAYLOAD);
  }
  const hasBody = body !== null && body !== undefined;
  const computePayloadHash = !headers.has(AMZ_CONTENT_SHA256_HEADER);
  const materialize = (options.replay && shouldMaterializeBodyForReplay(body)) || (computePayloadHash && hasBody);
  const prepared = await prepareBody(body, headers, materialize, options.signal);
  let payloadHash = headers.get(AMZ_CONTENT_SHA256_HEADER);
  if (payloadHash === null) {
    if (prepared.bytes === undefined) {
      throw new Error("body bytes must be materialized before payload hashing");
    }
    payloadHash = await sha256Hex(prepared.bytes);
    options.signal?.throwIfAborted();
    if (hasBody || options.service === "s3") {
      headers.set(AMZ_CONTENT_SHA256_HEADER, payloadHash);
    }
  }
  return { body: prepared.body, payloadHash };
}

async function prepareBody(
  body: BodyInit | null | undefined,
  headers: Headers,
  materialize: boolean,
  signal?: AbortSignal
): Promise<MaterializedBody> {
  signal?.throwIfAborted();
  assertSupportedBody(body);
  if (body === null || body === undefined) {
    return { body, bytes: new Uint8Array() };
  }
  if (body instanceof FormData) {
    rejectManualFormDataContentType(headers);
    const request = new Request("https://aws-sigv4.invalid/", { method: "POST", body });
    const contentType = request.headers.get(CONTENT_TYPE_HEADER);
    if (contentType) {
      headers.set(CONTENT_TYPE_HEADER, contentType);
    }
    const bytes =
      signal && request.body
        ? await readStreamBytes(request.body, signal)
        : new Uint8Array(await request.arrayBuffer());
    signal?.throwIfAborted();
    return { body: bytes, bytes };
  }
  setGeneratedContentType(body, headers);
  if (body instanceof ReadableStream) {
    assertReadableStreamUsable(body);
    if (!materialize) {
      return { body };
    }
    const bytes = await readStreamBytes(body, signal);
    return { body: bytes, bytes };
  }
  if (!materialize && (typeof body === "string" || body instanceof Blob)) {
    return { body };
  }
  const bytes = await bodyBytes(body, signal);
  signal?.throwIfAborted();
  return { body: stableMaterializedBody(body, bytes), bytes };
}

function shouldMaterializeBodyForReplay(body: BodyInit | null | undefined): boolean {
  return body !== undefined && body !== null && typeof body !== "string" && !(body instanceof Blob);
}

function rejectManualFormDataContentType(headers: Headers): void {
  if (headers.has(CONTENT_TYPE_HEADER)) {
    throw new TypeError("FormData content-type must be generated by the runtime");
  }
}

function setGeneratedContentType(body: BodyInit, headers: Headers): void {
  if (headers.has(CONTENT_TYPE_HEADER)) {
    return;
  }
  if (typeof body === "string") {
    headers.set(CONTENT_TYPE_HEADER, "text/plain;charset=UTF-8");
  } else if (body instanceof URLSearchParams) {
    headers.set(CONTENT_TYPE_HEADER, "application/x-www-form-urlencoded;charset=UTF-8");
  } else if (body instanceof Blob) {
    if (body.type) {
      headers.set(CONTENT_TYPE_HEADER, body.type);
    }
  }
}

async function bodyBytes(body: BodyInit, signal?: AbortSignal): Promise<Uint8Array> {
  if (typeof body === "string") {
    return textEncoder.encode(body);
  }
  if (body instanceof ArrayBuffer) {
    return new Uint8Array(body).slice();
  }
  if (body instanceof Uint8Array) {
    // Resizing can make a fixed-length view out of bounds while its public
    // offset and length read as zero. Validate the internal view before copying,
    // then use intrinsic getters so subclass accessors cannot alter the snapshot.
    void Uint8Array.prototype.at.call(body, 0);
    const buffer = Reflect.get(typedArrayPrototype, "buffer", body) as ArrayBufferLike;
    const byteOffset = Reflect.get(typedArrayPrototype, "byteOffset", body) as number;
    const byteLength = Reflect.get(typedArrayPrototype, "byteLength", body) as number;
    return new Uint8Array(buffer, byteOffset, byteLength).slice();
  }
  if (ArrayBuffer.isView(body)) {
    // Copy through a fresh base view so input-owned slice methods and subclass
    // species cannot affect the snapshot. Copy performance varies by engine;
    // this form follows the bulk-copy path in the pinned workerd runtime.
    return new Uint8Array(body.buffer, body.byteOffset, body.byteLength).slice();
  }
  if (body instanceof URLSearchParams) {
    return textEncoder.encode(body.toString());
  }
  if (body instanceof Blob) {
    if (signal) {
      return readStreamBytes(body.stream(), signal);
    }
    return new Uint8Array(await body.arrayBuffer());
  }
  throw new TypeError("body must be a string, Blob, URLSearchParams, ArrayBuffer, or ArrayBufferView");
}

function assertReadableStreamUsable(body: ReadableStream): void {
  try {
    void new Response(body);
  } catch (error) {
    if (error instanceof TypeError) {
      throw new TypeError("ReadableStream body must not be disturbed or locked", { cause: error });
    }
    throw error;
  }
}

async function readStreamBytes(
  stream: ReadableStream<unknown>,
  signal?: AbortSignal
): Promise<Uint8Array<ArrayBuffer>> {
  const reader = stream.getReader();
  const chunks: Uint8Array<ArrayBuffer>[] = [];
  let byteLength = 0;
  const onAbort = () => {
    if (signal) {
      void reader.cancel(signal.reason).catch(() => undefined);
    }
  };
  signal?.addEventListener("abort", onAbort, { once: true });
  try {
    for (;;) {
      signal?.throwIfAborted();
      const result = await reader.read();
      signal?.throwIfAborted();
      if (result.done) {
        break;
      }
      const value = result.value;
      if (!(value instanceof Uint8Array)) {
        throw new TypeError("ReadableStream body must yield Uint8Array chunks");
      }
      const chunk = new Uint8Array(value);
      chunks.push(chunk);
      byteLength += chunk.byteLength;
    }
  } catch (err) {
    if (signal?.aborted) {
      throw signal.reason;
    }
    void reader.cancel(err).catch(() => undefined);
    throw err;
  } finally {
    signal?.removeEventListener("abort", onAbort);
    reader.releaseLock();
  }
  const bytes = new Uint8Array(byteLength);
  let offset = 0;
  for (const chunk of chunks) {
    bytes.set(chunk, offset);
    offset += chunk.byteLength;
  }
  return bytes;
}

function isAsyncIterable(value: unknown): value is AsyncIterable<unknown> {
  return typeof (value as { [Symbol.asyncIterator]?: unknown })[Symbol.asyncIterator] === "function";
}

function assertSupportedBody(body: BodyInit | null | undefined): void {
  if (body === null || body === undefined) {
    return;
  }
  if (
    typeof body === "string" ||
    body instanceof Blob ||
    body instanceof FormData ||
    body instanceof ReadableStream ||
    body instanceof URLSearchParams ||
    body instanceof ArrayBuffer ||
    ArrayBuffer.isView(body)
  ) {
    return;
  }
  if (isAsyncIterable(body)) {
    throw new TypeError("async iterable bodies are not supported; use a ReadableStream");
  }
  throw new TypeError("body must be a string, Blob, URLSearchParams, ArrayBuffer, or ArrayBufferView");
}

function stableMaterializedBody(body: BodyInit, bytes: Uint8Array): BodyInit {
  if (typeof body === "string") {
    return body;
  }
  if (bytes.buffer instanceof ArrayBuffer) {
    return bytes as Uint8Array<ArrayBuffer>;
  }
  return new Uint8Array(bytes);
}
