// SPDX-FileCopyrightText: 2026 Sean Consulting OÜ
// SPDX-License-Identifier: Apache-2.0

import { CONTENT_TYPE_HEADER, textEncoder } from "./constants.js";

export interface PreparedBody {
  body: BodyInit | null | undefined;
  bytes: Uint8Array;
}

export async function prepareBody(
  body: BodyInit | null | undefined,
  headers: Headers,
  materialize: boolean
): Promise<PreparedBody> {
  if (body === null || body === undefined) {
    return { body, bytes: new Uint8Array() };
  }
  if (body instanceof FormData) {
    rejectManualFormDataContentType(headers);
    const request = new Request("https://aws-sigv4.invalid/", { method: "POST", body });
    const contentType = request.headers.get(CONTENT_TYPE_HEADER);
    if (contentType) {
      headers.set(CONTENT_TYPE_HEADER, contentType);
    }
    const bytes = new Uint8Array(await request.arrayBuffer());
    return { body: bytes, bytes };
  }
  setGeneratedContentType(body, headers);
  if (!materialize) {
    return { body, bytes: new Uint8Array() };
  }
  if (body instanceof ReadableStream) {
    const bytes = new Uint8Array(await new Response(body).arrayBuffer());
    return { body: bytes, bytes };
  }
  const bytes = await bodyBytes(body);
  return { body: stableMaterializedBody(body, bytes), bytes };
}

function rejectManualFormDataContentType(headers: Headers): void {
  if (headers.has(CONTENT_TYPE_HEADER)) {
    throw new TypeError("FormData content-type must be generated by the runtime");
  }
}

function setGeneratedContentType(body: BodyInit, headers: Headers): void {
  if (headers.has(CONTENT_TYPE_HEADER)) {
    return;
  }
  if (typeof body === "string") {
    headers.set(CONTENT_TYPE_HEADER, "text/plain;charset=UTF-8");
  } else if (body instanceof URLSearchParams) {
    headers.set(CONTENT_TYPE_HEADER, "application/x-www-form-urlencoded;charset=UTF-8");
  } else if (body instanceof Blob && body.type) {
    headers.set(CONTENT_TYPE_HEADER, body.type);
  }
}

async function bodyBytes(body: BodyInit): Promise<Uint8Array> {
  if (typeof body === "string") {
    return textEncoder.encode(body);
  }
  if (body instanceof Uint8Array) {
    return body;
  }
  if (body instanceof ArrayBuffer) {
    return new Uint8Array(body);
  }
  if (ArrayBuffer.isView(body)) {
    return new Uint8Array(body.buffer, body.byteOffset, body.byteLength);
  }
  if (body instanceof URLSearchParams) {
    return textEncoder.encode(body.toString());
  }
  if (body instanceof Blob) {
    return new Uint8Array(await body.arrayBuffer());
  }
  throw new TypeError("body must be a string, Blob, URLSearchParams, ArrayBuffer, or ArrayBufferView");
}

function stableMaterializedBody(body: BodyInit, bytes: Uint8Array): BodyInit {
  if (typeof body === "string" || body instanceof Uint8Array) {
    return body;
  }
  if (bytes.buffer instanceof ArrayBuffer) {
    return bytes as Uint8Array<ArrayBuffer>;
  }
  return new Uint8Array(bytes);
}
