// SPDX-FileCopyrightText: 2026 Sean Consulting OÜ
// SPDX-License-Identifier: Apache-2.0

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  FIXED_AMZ_DATE,
  LAMBDA_ENDPOINT,
  S3_ENDPOINT,
  lambdaClient,
  lambdaRequest,
  s3Client,
  s3Request,
} from "./helpers.js";

test("SigV4Client.sign supports FormData bodies", async () => {
  const client = lambdaClient();
  const form = new FormData();
  form.set("message", "hello");
  const signed = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: form,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.match(signed.headers.get("content-type") || "", /^multipart\/form-data; boundary=/);
  assert.match(await signed.clone().text(), /name="message"/);
  assert.match(
    signed.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
});

test("SigV4Client.sign rejects manual FormData content-type", async () => {
  const client = lambdaClient();
  const form = new FormData();
  form.set("message", "hello");
  for (const contentType of ["multipart/form-data", "multipart/form-data; boundary=manual"]) {
    await assert.rejects(
      () =>
        client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
          method: "POST",
          headers: {
            "content-type": contentType,
          },
          body: form,
          signing: { signingDate: FIXED_AMZ_DATE },
        }),
      /FormData content-type must be generated by the runtime/
    );
  }
});

test("S3 unsigned FormData rejects manual content-type", async () => {
  const client = s3Client();
  const form = new FormData();
  form.set("message", "hello");
  await assert.rejects(
    () =>
      client.sign(`${S3_ENDPOINT}/example-bucket/form-data.txt`, {
        method: "PUT",
        headers: {
          "content-type": "multipart/form-data; boundary=manual",
        },
        body: form,
        signing: { signingDate: FIXED_AMZ_DATE },
      }),
    /FormData content-type must be generated by the runtime/
  );
});

test("SigV4Client.sign supports ReadableStream bodies", async () => {
  const client = lambdaClient();
  const body = new ReadableStream({
    start(controller) {
      controller.enqueue(new TextEncoder().encode("hello"));
      controller.close();
    },
  });
  const signed = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(await signed.clone().text(), "hello");
  assert.match(signed.headers.get("authorization") || "", /SignedHeaders=host;x-amz-content-sha256;x-amz-date/);
});

test("payload hashing cancels streams that yield invalid chunks", async () => {
  let cancelReason;
  const body = new ReadableStream({
    start(controller) {
      controller.enqueue(new Int8Array([1]));
    },
    cancel(reason) {
      cancelReason = reason;
    },
  });
  await assert.rejects(
    () =>
      lambdaRequest({
        method: "POST",
        url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
        body,
      }),
    /ReadableStream body must yield Uint8Array chunks/
  );
  assert.match(cancelReason?.message || "", /ReadableStream body must yield Uint8Array chunks/);
  assert.equal(body.locked, false);
});

test("payload hashing sends stable URLSearchParams bytes", async () => {
  const body = new URLSearchParams({ a: "1" });
  const client = lambdaClient();
  const pending = client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  body.set("a", "2");
  const signed = await pending;
  assert.equal(await signed.text(), "a=1");
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "c22fea5d7428e5cf47ef6354c97c9223c95d6dcdc3e0d2300ff79056b1ff3d85"
  );
});

test("payload hashing sends stable Blob bytes", async () => {
  const client = lambdaClient();
  const body = new Blob(["blob=1"], { type: "text/plain" });
  const signal = new AbortController().signal;
  const signed = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body,
    signal,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(signed.headers.get("content-type"), "text/plain");
  assert.equal(await signed.text(), "blob=1");
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "ff6f2bbd6e6921803074834e09a2372e15f5ab7d4b962d23e38c98d5d97696ee"
  );
});

test("SigV4Client.sign snapshots mutable headers and bytes before returning", async () => {
  const headers = new Headers({ "x-before": "yes" });
  const body = new TextEncoder().encode("one");
  const pending = lambdaClient().sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    headers,
    body,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  headers.set("x-after", "must-not-be-signed");
  body.set(new TextEncoder().encode("two"));
  const signed = await pending;
  assert.equal(signed.headers.get("x-before"), "yes");
  assert.equal(signed.headers.get("x-after"), null);
  assert.match(signed.headers.get("authorization") || "", /x-before/);
  assert.doesNotMatch(signed.headers.get("authorization") || "", /x-after/);
  assert.equal(await signed.text(), "one");
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "7692c3ad3540bb803c020b3aee66cd8887123234ea0c6e7143c0add73ff431ed"
  );
});

test("SigV4Client.sign does not fully buffer unsigned S3 Request streams", async () => {
  let pulls = 0;
  const body = new ReadableStream({
    pull(controller) {
      pulls += 1;
      controller.enqueue(new TextEncoder().encode(String(pulls)));
      if (pulls === 3) {
        controller.close();
      }
    },
  });
  const request = new Request(`${S3_ENDPOINT}/example-bucket/large-upload.bin`, {
    method: "PUT",
    body,
    duplex: "half",
  });
  const client = s3Client();
  const signed = await client.sign(request, {
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.ok(pulls < 3);
  assert.equal(signed.headers.get("x-amz-content-sha256"), "UNSIGNED-PAYLOAD");
  assert.equal(await signed.text(), "123");
  assert.equal(pulls, 3);
  assert.equal(request.bodyUsed, true);
  await assert.rejects(() => request.text(), /Body has already been read|unusable|locked/iu);
});

test("SigV4Client.fetch does not fully buffer unsigned S3 Request streams by default", async () => {
  let pulls = 0;
  const body = new ReadableStream({
    pull(controller) {
      pulls += 1;
      controller.enqueue(new TextEncoder().encode(String(pulls)));
      if (pulls === 3) {
        controller.close();
      }
    },
  });
  const request = new Request(`${S3_ENDPOINT}/example-bucket/large-upload.bin`, {
    method: "PUT",
    body,
    duplex: "half",
  });
  const client = s3Client({
    fetch: async (signed) => {
      assert.ok(pulls < 3);
      assert.equal(signed.headers.get("x-amz-content-sha256"), "UNSIGNED-PAYLOAD");
      assert.equal(await signed.text(), "123");
      return new Response("ok");
    },
  });
  const response = await client.fetch(request, {
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(response.status, 200);
  assert.equal(pulls, 3);
  assert.equal(request.bodyUsed, true);
  await assert.rejects(() => request.text(), /Body has already been read|unusable|locked/iu);
});

test("body materialization cancels promptly and preserves the exact abort reason", { timeout: 2_000 }, async () => {
  let readStartedResolve;
  const readStarted = new Promise((resolve) => {
    readStartedResolve = resolve;
  });
  let cancelReason;
  const body = new ReadableStream({
    pull() {
      readStartedResolve();
    },
    cancel(reason) {
      cancelReason = reason;
    },
  });
  const controller = new AbortController();
  const reason = { code: "stop-materializing" };
  let fetchCalls = 0;
  const client = lambdaClient({
    fetch: async () => {
      fetchCalls += 1;
      return new Response("unreachable");
    },
  });
  const pending = client.fetch(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body,
    signal: controller.signal,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  await readStarted;
  controller.abort(reason);
  let caught;
  try {
    await pending;
  } catch (err) {
    caught = err;
  }
  assert.equal(caught, reason);
  assert.equal(cancelReason, reason);
  assert.equal(fetchCalls, 0);
});

test("fetch body materialization inherits a Request input signal", async () => {
  let pulls = 0;
  const body = new ReadableStream(
    {
      pull() {
        pulls += 1;
        return new Promise(() => {});
      },
    },
    { highWaterMark: 0 }
  );
  const controller = new AbortController();
  const reason = { code: "request-input-abort" };
  controller.abort(reason);
  const request = new Request(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body,
    duplex: "half",
    signal: controller.signal,
  });
  let fetchCalls = 0;
  const client = lambdaClient({
    fetch: async () => {
      fetchCalls += 1;
      return new Response("unreachable");
    },
  });
  let caught;
  try {
    await client.fetch(request, { signing: { signingDate: FIXED_AMZ_DATE } });
  } catch (error) {
    caught = error;
  }
  assert.equal(caught, reason);
  assert.equal(pulls, 0);
  assert.equal(fetchCalls, 0);
});

test("an explicit null signal does not inherit the Request input signal", async () => {
  const controller = new AbortController();
  controller.abort("ignored-input-abort");
  const request = new Request(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: "hello",
    signal: controller.signal,
  });
  let fetchedBody;
  const response = await lambdaClient({
    fetch: async (signed) => {
      fetchedBody = await signed.text();
      return new Response("ok");
    },
  }).fetch(request, {
    signal: null,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(response.status, 200);
  assert.equal(fetchedBody, "hello");
});

test("async iterable bodies are rejected before transport", async () => {
  let iterations = 0;
  const body = {
    async *[Symbol.asyncIterator]() {
      iterations += 1;
      yield "hello";
    },
  };
  let fetchCalls = 0;
  const client = s3Client({
    retries: 1,
    fetch: async () => {
      fetchCalls += 1;
      return new Response("unreachable");
    },
  });
  await assert.rejects(
    () =>
      client.fetch(`${S3_ENDPOINT}/example-bucket/async-iterable.txt`, {
        method: "PUT",
        body,
        duplex: "half",
        signing: { signingDate: FIXED_AMZ_DATE },
      }),
    /async iterable bodies are not supported/
  );
  assert.equal(iterations, 0);
  assert.equal(fetchCalls, 0);
});

test("unsupported body objects are rejected with a stable error", async () => {
  const attempts = [
    () =>
      lambdaRequest({
        method: "POST",
        url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
        body: {},
      }),
    () =>
      s3Request({
        method: "PUT",
        url: `${S3_ENDPOINT}/example-bucket/unsupported-body.txt`,
        body: {},
      }),
    () =>
      s3Client().sign(`${S3_ENDPOINT}/example-bucket/unsupported-body.txt`, {
        method: "PUT",
        body: {},
        signing: { signAllHeaders: true, signingDate: FIXED_AMZ_DATE },
      }),
  ];
  for (const attempt of attempts) {
    await assert.rejects(attempt, /body must be a string, Blob, URLSearchParams, ArrayBuffer, or ArrayBufferView/);
  }
});

test("explicit x-amz-content-sha256 controls the canonical payload hash", async () => {
  const signed = await lambdaRequest({
    method: "POST",
    url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
    headers: {
      "content-type": "application/json",
      "x-amz-content-sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    },
    body: "ignored",
  });
  assert.equal(
    signed.headers.get("authorization"),
    "AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20260616/ap-northeast-1/lambda/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=20c8af3e452c87173cbbc0cdf9dcdd703dfcf7b03a11ec2c86ae8139f886cbc4"
  );
});

test("non-S3 requests can explicitly use unsigned payload signing", async () => {
  const signed = await lambdaRequest({
    method: "POST",
    url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
    headers: {
      "content-type": "application/json",
    },
    body: "{}",
    unsignedPayload: true,
  });
  assert.equal(signed.headers.get("x-amz-content-sha256"), "UNSIGNED-PAYLOAD");
  assert.equal(
    signed.headers.get("authorization"),
    "AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20260616/ap-northeast-1/lambda/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=cb3997d7146ebb9140d2a079b18124048546a81665d3e85acb1e6b6b494f9e69"
  );
});

test("generated content-type headers are included in signed headers", async () => {
  const client = lambdaClient();
  const params = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: new URLSearchParams({ hello: "world" }),
    signing: { signingDate: FIXED_AMZ_DATE, signAllHeaders: true },
  });
  assert.equal(params.headers.get("content-type"), "application/x-www-form-urlencoded;charset=UTF-8");
  assert.match(
    params.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );

  const blob = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: new Blob(["hello"], { type: "text/plain" }),
    signing: { signingDate: FIXED_AMZ_DATE, signAllHeaders: true },
  });
  assert.equal(blob.headers.get("content-type"), "text/plain");
  assert.match(
    blob.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
});

test("S3 unsigned FormData signs the generated boundary", async () => {
  const client = s3Client();
  const form = new FormData();
  form.set("message", "hello");
  const signed = await client.sign(`${S3_ENDPOINT}/example-bucket/form-data.txt`, {
    method: "PUT",
    body: form,
    signing: { signingDate: FIXED_AMZ_DATE, signAllHeaders: true },
  });
  const contentType = signed.headers.get("content-type") || "";
  const boundary = /boundary=(.+)$/u.exec(contentType)?.[1];
  assert.match(contentType, /^multipart\/form-data; boundary=/);
  assert.match(
    signed.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
  assert.ok(boundary);
  assert.match(await signed.clone().text(), new RegExp(boundary));
});

test("payload hashing snapshots Uint8Array bodies before asynchronous digest completion", async () => {
  const body = new Uint8Array([123, 34, 111, 107, 34, 58, 116, 114, 117, 101, 125]);
  const expectedBody = new Uint8Array(body);
  const digestInputs = [];
  const originalDigest = crypto.subtle.digest.bind(crypto.subtle);
  crypto.subtle.digest = async (algorithm, data) => {
    digestInputs.push(data);
    const digest = await originalDigest(algorithm, data);
    body.fill(66);
    return digest;
  };
  let signed;
  try {
    signed = await lambdaRequest({
      method: "POST",
      url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
      headers: {
        "content-type": "application/json",
      },
      body,
    });
  } finally {
    crypto.subtle.digest = originalDigest;
  }
  assert.equal(digestInputs.includes(body), false);
  assert.notEqual(signed.body, body);
  assert.deepEqual(signed.body, expectedBody);
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "4062edaf750fb8074e7e83e0c9028c94e32468a8b6f1614774328ef045150f93"
  );
});

test("payload hashing materializes ArrayBuffer bodies as Uint8Array", async () => {
  const body = new TextEncoder().encode('{"ok":true}').buffer;
  const signed = await lambdaRequest({
    method: "POST",
    url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
    headers: {
      "content-type": "application/json",
    },
    body,
  });
  assert.ok(signed.body instanceof Uint8Array);
  assert.notEqual(signed.body.buffer, body);
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "4062edaf750fb8074e7e83e0c9028c94e32468a8b6f1614774328ef045150f93"
  );
});

test("payload hashing snapshots ArrayBufferView bodies", async () => {
  const buffer = new ArrayBuffer(8);
  const body = new DataView(buffer, 2, 4);
  new Uint8Array(buffer).set([0, 0, 104, 101, 108, 112, 0, 0]);
  const signed = await lambdaRequest({
    method: "POST",
    url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
    body,
  });
  new Uint8Array(buffer).fill(0);
  assert.equal(new TextDecoder().decode(signed.body), "help");
  assert.notEqual(signed.body.buffer, buffer);
});

test("signed S3 payloads send x-amz-content-sha256", async () => {
  const signed = await s3Request({
    method: "PUT",
    url: `${S3_ENDPOINT}/example-bucket/signed-payload.txt`,
    body: "hello",
    unsignedPayload: false,
  });
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
  );
  assert.match(
    signed.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
});

test("signed empty S3 payloads send the empty SHA-256 hash", async () => {
  const signed = await s3Request({
    method: "GET",
    url: `${S3_ENDPOINT}/example-bucket/empty.txt`,
    unsignedPayload: false,
  });
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855"
  );
  assert.match(signed.headers.get("authorization") || "", /SignedHeaders=host;x-amz-content-sha256;x-amz-date/);
});
