// SPDX-FileCopyrightText: 2026 Sean Consulting OÜ
// SPDX-License-Identifier: Apache-2.0

import assert from "node:assert/strict";
import { test } from "node:test";

import {
  FIXED_AMZ_DATE,
  LAMBDA_ENDPOINT,
  S3_ENDPOINT,
  lambdaClient,
  lambdaRequest,
  s3Client,
  s3Request,
} from "./helpers.js";

test("SigV4Client.sign supports FormData bodies", async () => {
  const client = lambdaClient();
  const form = new FormData();
  form.set("message", "hello");
  const signed = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: form,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.match(signed.headers.get("content-type") || "", /^multipart\/form-data; boundary=/);
  assert.match(await signed.clone().text(), /name="message"/);
  assert.match(
    signed.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
});

test("SigV4Client.sign rejects manual FormData content-type", async () => {
  const client = lambdaClient();
  const form = new FormData();
  form.set("message", "hello");
  for (const contentType of ["multipart/form-data", "multipart/form-data; boundary=manual"]) {
    await assert.rejects(
      () =>
        client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
          method: "POST",
          headers: {
            "content-type": contentType,
          },
          body: form,
          signing: { signingDate: FIXED_AMZ_DATE },
        }),
      /FormData content-type must be generated by the runtime/
    );
  }
});

test("S3 unsigned FormData rejects manual content-type", async () => {
  const client = s3Client();
  const form = new FormData();
  form.set("message", "hello");
  await assert.rejects(
    () =>
      client.sign(`${S3_ENDPOINT}/example-bucket/form-data.txt`, {
        method: "PUT",
        headers: {
          "content-type": "multipart/form-data; boundary=manual",
        },
        body: form,
        signing: { signingDate: FIXED_AMZ_DATE },
      }),
    /FormData content-type must be generated by the runtime/
  );
});

test("SigV4Client.sign supports ReadableStream bodies", async () => {
  const client = lambdaClient();
  const body = new ReadableStream({
    start(controller) {
      controller.enqueue(new TextEncoder().encode("hello"));
      controller.close();
    },
  });
  const signed = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body,
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(await signed.clone().text(), "hello");
  assert.match(signed.headers.get("authorization") || "", /SignedHeaders=host;x-amz-content-sha256;x-amz-date/);
});

test("hashed URLSearchParams bodies send the signed bytes", async () => {
  class UnstableParams extends URLSearchParams {
    calls = 0;

    toString() {
      this.calls += 1;
      return this.calls === 1 ? "a=1" : "a=2";
    }
  }
  const client = lambdaClient();
  const signed = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: new UnstableParams(),
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(await signed.text(), "a=1");
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "c22fea5d7428e5cf47ef6354c97c9223c95d6dcdc3e0d2300ff79056b1ff3d85"
  );
});

test("hashed Blob bodies send the signed bytes", async () => {
  class UnstableBlob extends Blob {
    calls = 0;

    async arrayBuffer() {
      this.calls += 1;
      return new TextEncoder().encode(this.calls === 1 ? "blob=1" : "blob=2").buffer;
    }
  }
  const client = lambdaClient();
  const signed = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: new UnstableBlob([], { type: "text/plain" }),
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(await signed.text(), "blob=1");
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "ff6f2bbd6e6921803074834e09a2372e15f5ab7d4b962d23e38c98d5d97696ee"
  );
});

test("SigV4Client.sign does not fully buffer unsigned S3 Request streams", async () => {
  let pulls = 0;
  const body = new ReadableStream({
    pull(controller) {
      pulls += 1;
      controller.enqueue(new TextEncoder().encode(String(pulls)));
      if (pulls === 3) {
        controller.close();
      }
    },
  });
  const request = new Request(`${S3_ENDPOINT}/example-bucket/large-upload.bin`, {
    method: "PUT",
    body,
    duplex: "half",
  });
  const client = s3Client();
  const signed = await client.sign(request, {
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.ok(pulls < 3);
  assert.equal(signed.headers.get("x-amz-content-sha256"), "UNSIGNED-PAYLOAD");
  assert.equal(await signed.text(), "123");
  assert.equal(pulls, 3);
});

test("SigV4Client.fetch does not fully buffer unsigned S3 Request streams by default", async () => {
  let pulls = 0;
  const body = new ReadableStream({
    pull(controller) {
      pulls += 1;
      controller.enqueue(new TextEncoder().encode(String(pulls)));
      if (pulls === 3) {
        controller.close();
      }
    },
  });
  const request = new Request(`${S3_ENDPOINT}/example-bucket/large-upload.bin`, {
    method: "PUT",
    body,
    duplex: "half",
  });
  const client = s3Client({
    fetch: async (signed) => {
      assert.ok(pulls < 3);
      assert.equal(signed.headers.get("x-amz-content-sha256"), "UNSIGNED-PAYLOAD");
      assert.equal(await signed.text(), "123");
      return new Response("ok");
    },
  });
  const response = await client.fetch(request, {
    signing: { signingDate: FIXED_AMZ_DATE },
  });
  assert.equal(response.status, 200);
  assert.equal(pulls, 3);
});

test("explicit x-amz-content-sha256 controls the canonical payload hash", async () => {
  const signed = await lambdaRequest({
    method: "POST",
    url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
    headers: {
      "content-type": "application/json",
      "x-amz-content-sha256": "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
    },
    body: "ignored",
  });
  assert.equal(
    signed.headers.get("authorization"),
    "AWS4-HMAC-SHA256 Credential=AKIDEXAMPLE/20260616/ap-northeast-1/lambda/aws4_request, SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date, Signature=20c8af3e452c87173cbbc0cdf9dcdd703dfcf7b03a11ec2c86ae8139f886cbc4"
  );
});

test("generated content-type headers are signed before Request construction", async () => {
  const client = lambdaClient();
  const params = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: new URLSearchParams({ hello: "world" }),
    signing: { signingDate: FIXED_AMZ_DATE, signAllHeaders: true },
  });
  assert.equal(params.headers.get("content-type"), "application/x-www-form-urlencoded;charset=UTF-8");
  assert.match(
    params.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );

  const blob = await client.sign(`${LAMBDA_ENDPOINT}/2025-09-09/microvms`, {
    method: "POST",
    body: new Blob(["hello"], { type: "text/plain" }),
    signing: { signingDate: FIXED_AMZ_DATE, signAllHeaders: true },
  });
  assert.equal(blob.headers.get("content-type"), "text/plain");
  assert.match(
    blob.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
});

test("S3 unsigned FormData signs the generated boundary", async () => {
  const client = s3Client();
  const form = new FormData();
  form.set("message", "hello");
  const signed = await client.sign(`${S3_ENDPOINT}/example-bucket/form-data.txt`, {
    method: "PUT",
    body: form,
    signing: { signingDate: FIXED_AMZ_DATE, signAllHeaders: true },
  });
  const contentType = signed.headers.get("content-type") || "";
  const boundary = /boundary=(.+)$/u.exec(contentType)?.[1];
  assert.match(contentType, /^multipart\/form-data; boundary=/);
  assert.match(
    signed.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
  assert.ok(boundary);
  assert.match(await signed.clone().text(), new RegExp(boundary));
});

test("payload hashing reuses Uint8Array bodies without copying", async () => {
  const body = new Uint8Array([123, 34, 111, 107, 34, 58, 116, 114, 117, 101, 125]);
  const digestInputs = [];
  const originalDigest = crypto.subtle.digest.bind(crypto.subtle);
  crypto.subtle.digest = async (algorithm, data) => {
    digestInputs.push(data);
    return originalDigest(algorithm, data);
  };
  try {
    await lambdaRequest({
      method: "POST",
      url: `${LAMBDA_ENDPOINT}/2025-09-09/microvms`,
      headers: {
        "content-type": "application/json",
      },
      body,
    });
  } finally {
    crypto.subtle.digest = originalDigest;
  }
  assert.equal(digestInputs.includes(body), true);
});

test("signed S3 payloads send x-amz-content-sha256", async () => {
  const signed = await s3Request({
    method: "PUT",
    url: `${S3_ENDPOINT}/example-bucket/signed-payload.txt`,
    body: "hello",
    unsignedPayload: false,
  });
  assert.equal(
    signed.headers.get("x-amz-content-sha256"),
    "2cf24dba5fb0a30e26e83b2ac5b9e29e1b161e5c1fa7425e73043362938b9824"
  );
  assert.match(
    signed.headers.get("authorization") || "",
    /SignedHeaders=content-type;host;x-amz-content-sha256;x-amz-date/
  );
});
